### ISSUE TITLE
Add MinimumLogLevel setting to SetupLog (also to Hercules and other)

### ISSUE THREAD

**Issue by kungasc** [vostok/hosting#35]
Now you need to use decorator:
```
.SetupLog(l => l.CustomizeLog(ll => ll.WithMinimumLevel(...)))
```
and can't return this action back.
Also this level should be logged before being applied.

**Comment by kungasc** [comment]
https://kontur.slack.com/archives/C08DRHZTP/p1604071146094100
https://kontur.slack.com/archives/C08DRHZTP/p1605074794354800

**Comment by HolyPrapor** [comment]
This could be implemented through LogConfigurationRule {MinimumLevel = ...}.

Therefore, this issue is related to [this one](https://github.com/vostok/hosting/issues/38).

Although, this will not make you able to revert applied rules.

**Comment by kungasc** [comment]
Done in https://github.com/vostok/hosting/pull/43. Use `SetupMinimumLevelProvider` instead of `CustomizeLog`.
