### ISSUE TITLE
Allow to specify additional local IPs or override local datacenter to support containerized workloads

### ISSUE THREAD

**Issue by iloktionov** [vostok/hosting#4]
Current ideas:
- Automatically pick up the value of `VOSTOK_LOCAL_DATACENTER` environment variable.
- Automatically pick up the value of `VOSTOK_LOCAL_HOSTNAME` environment variable.
- Provide APIs to manually override local datacenter in code.

**Comment by kungasc** [comment]
Automatically pick up the value of `VOSTOK_LOCAL_HOSTNAME` environment variable.

**Comment by kungasc** [comment]
Done.
